imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    #database_path: '%kernel.root_dir%/../../../build/test.db'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User

easy_admin:
    site_name: 'Admin Panel'

    design:
        brand_color: '#c951e7'
        menu:
            - {label: 'Home', url: 'http://127.0.0.1:8000' ,icon: 'home' }
            - {entity: 'User', icon: 'user'}
            - {entity: 'Coach', icon: 'user'}
            - {entity: 'Klant', icon: 'user'}
            - {label: 'Logout', url: 'http://127.0.0.1:8000/logout' ,icon: 'log-out' }

    list:
        actions:

            - { name: 'edit',icon: 'pencil', label: 'Edit' }
            - { name: 'delete',icon: 'trash', label: 'Delete' }
            - { name: 'search',icon: 'trash', label: 'Search' }
            - { name: 'new', label: 'New' }

    #entities:
       # - AppBundle\Entity\User
       # - AppBundle\Entity\Coach
       # - AppBundle\Entity\Klant

#easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
            label: 'User'
            list:
                title: "Users"
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'username', label: 'Naam'}
                    - {property: 'email', label: 'Email'}
                    - {property: 'enabled', label: 'inschakelen'}
                    - {property: 'last_login', label: 'laatste login'}
                    - {property: 'locked', label: 'Lock'}
                    - {property: 'roles', label: 'Rolen'}

            edit:
                title: 'Edit User'
                fields: ['username', 'email', 'roles', 'enabled', 'locked']
            new:
                title: 'Add new User'
                fields:
                    - { property: 'username' }
                    - { property: 'email', type: 'email', label: 'E-mail address' }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'roles'}
                    - { property: 'enabled'}
                    - { property: 'locked'}
        Coach:
            class: AppBundle\Entity\Coach
            list:
                title: "Coaches"
            new:
                title: 'Add new Coach'
                fields: ['user', 'naam', 'email']
            edit:
                 title: 'Edit Coach'
        Klant:
            class: AppBundle\Entity\Klant
            list:
                title: "Klanten"
            new:
                title: 'Add new Klant'
                fields: ['user', 'naam', 'habit1', 'habit2', 'habit3']
            disabled_actions: ['edit']