# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
app.klant_service:
    class: 'AppBundle\Service\Klant'
    arguments: [ "@doctrine.orm.entity_manager", "@app.klant_Repository"]

    app.klant_repository:
    class: Doctrin\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manger", "getRepository"]
    arguments: ['AppBundle\Entity\Klant']