<?php
/**
 * Created by PhpStorm.
 * User: Nida
 * Date: 28/10/2016
 * Time: 13:45
 */

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Klant;

class KlantRepository extends EntityRepository
{

    /*
 public function findAll()
 {
     return Klant::findAll(); // TODO: Change the autogenerated stub
 }
 */
}